<?php

use Illuminate\Database\Seeder;

use Faker\Factory as Faker;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void

     */
   
    public function run()
    {
        // $this->call(UsersTableSeeder::class);s
       

    	$faker = Faker::create();
    	foreach (range(1,10) as $index) {

    		DB::table('users')->insert([
    			'fname' => str_random(10),
    			'lname' => str_random(10),
    			'email' => str_random(10).'@gmail.com',
    			'password' => bcrypt('secret'),
    		]);

    		// for looping with the name and email automatically generated by the faker variable

    		// DB::table('users')->insert([
    		// 	'fname' => $faker->name,
    		// 	'lname' => $faker->name,
    		// 	'email' => $faker->email,
    		// 	'password' => bcrypt('secret'),
    		// ]);

    	// }
    		// for single enter with specified name 
    		// it needs factory faker to create the faker values
    	 // $user = factory(App\User::class)->create([
      //        'email' => 'admin@gmail.com',
      //        'password' => bcrypt('admin'),
      //        'fname' => 'Mr',
      //        'lname' => 'admin'
      //    ]);
    

}}}
